### ISSUE TITLE
datasets.json

### ISSUE THREAD

**Issue by tischi** [platybrowser/mmb-python#3]
@constantinpape 
Could you do me a favour and rename `default` to `defaultDataset`:
```
{
  "datasets": [
    "10spd",
    "10spdbaf"
  ],
  "defaultDataset": "10spdbaf"
}
```

`default` is reserved in Java and cannot be used as a variable name.

**Comment by constantinpape** [comment]
No problem, will change it in a sec.

**Comment by constantinpape** [comment]
Done.
