### ISSUE TITLE
Json

### ISSUE THREAD

**Issue by tischi** [platybrowser/mmb-python#4]
@constantinpape 
For the bookmarks, the keys in the jsons are currently capitalised, see e.g. here: https://github.com/platybrowser/platybrowser/blob/master/data/1.0.1/misc/bookmarks.json
In Java variable names "must" be lower-case, though. Thus if I want to directly read and write `Bookmark` objects, it would be simpler and cleaner if all keys were lower-case. 
Would that it be ok for you to change this?

If you however insist on them being capitalised I think I could make it work, as there seem to be tools for handling this: https://stackoverflow.com/questions/48707808/how-to-serialize-string-to-object-using-capitalized-field-names

**Comment by constantinpape** [comment]
Lower case is fine with me.

**Comment by constantinpape** [comment]
I have changed it in the autophagosoms repo now.
But I think we should change it in the `images.json` as well.
What do you think?

**Comment by tischi** [comment]
1. Thanks!
1. Yes, **all** MoBIE jsons should have **all** keys in lower case, I would say.

**Comment by constantinpape** [comment]
>     2\. Yes, **all** MoBIE jsons should have **all** keys in lower case, I would say.

Makes total sense!
I need to finish an email, after that I will update the `images.json` in the autophago rep as well.

**Comment by tischi** [comment]
And, since we are on it now, I wonder whether this is the best way of doing it:

```
{
  "default": {
    "layers": {
      "fibsem-10spd-raw": {
        "maxValue": 255,
        "minValue": 0
      }
    },
    "view": [
      2.0780252518726174E-17, -0.06639192399049879, 0.0, 559.9426540380047, 0.06639192399049879, 2.0780252518726174E-17, 0.0, 166.52295878859852, 0.0, 0.0, 0.06639192399049883, -16.55676959619953
    ]
  }
}
```

Somehow the "default" String is hanging in the air... maybe it is fine but could this be an alternative?

```
   [ { 
     "name": "default",
    "layers": {
      "fibsem-10spd-raw": {
        "maxValue": 255,
        "minValue": 0
      }
    },
    "view": [
      2.0780252518726174E-17, -0.06639192399049879, 0.0, 559.9426540380047, 0.06639192399049879, 2.0780252518726174E-17, 0.0, 166.52295878859852, 0.0, 0.0, 0.06639192399049883, -16.55676959619953
    ]
  ]
```

Essentially what would be an option is for this to be a list of `Bookmark`s. Seems to some confus
I guess what you have is a `Map< String, Bookmark > nameToBookmark`?

**Comment by tischi** [comment]
...in fact also inside the layers field, could we have a field for the `image`?
again, I think easier to parse into an `Object`.

```
"layers": {
        "image": "fibsem-10spd-raw",
        "maxValue": 255,
        "minValue": 0
      }
```

**Comment by tischi** [comment]
@constantinpape 

```
public static class Layer
{
	public String image = "imageName";
	public double maxValue = 100;
	public double minValue = 0;
}
```

Both would work for me, but the `List` is a bit more concise.

### Map< String, Layer >
```
{
  "imageA": {
    "image": "imageA",
    "maxValue": 100.0,
    "minValue": 0.0
  },
  "imageB": {
    "image": "imageB",
    "maxValue": 100.0,
    "minValue": 0.0
  }
}
```

### List< Layer > list

```
[
  {
    "image": "imageA",
    "maxValue": 100.0,
    "minValue": 0.0
  },
  {
    "image": "imageB",
    "maxValue": 100.0,
    "minValue": 0.0
  }
]
```

**Comment by tischi** [comment]
I guess we could also leave it as you have it, then I could have a `Map< String, LayerProperties > layerNameToLayerProperties`. Shall I call you? ;-)

**Comment by constantinpape** [comment]
> Shall I call you? ;-)

Give me 5 minutes and I can call you ;)

**Comment by constantinpape** [comment]
Ok, we discussed to leave the structure as it is, but to change everything to lower case, also in `images.json`
I have changed it in the autophagosomes repository now.

**Comment by tischi** [comment]
I am making some progress. This is what I have so far:
```
	public static class Bookmark
	{
		public HashMap< String, LayerProperties > layers;
		public double[] view;
		public double[] position;
	}

	public static class LayerProperties
	{
		public Storage storage; // only image
		public String type; // only image
                 public String tableFolder; // only image
		public String color;
		public double minValue; // => colorContrastLimits double[]?
		public double maxValue;
		public String colorMap;
		public double colorMapMinValue; // => colorMapContrastLimits double[] ?!
		public double colorMapMaxValue;
		public String colorByColumn; // only bookmark
		public ArrayList< String > tables; // only bookmark
		public ArrayList< Double > selectedLabelIds; // only bookmark
		public boolean showSelectedSegmentsIn3d; // only bookmark
		public boolean showImageIn3d; // only bookmark
	}

	public static class Storage
	{
		public String local;
		public String remote;
	}
```

1. Is this complete?
2. Are we happy with it? Now would be a good moment to change something?

I think it is a bit messy, because some of the LayerProperties only apply to the images.json while others only apply to the bookmarks.json. But I think for convenience I may have only one object for this...

Do we need `color` and `colorMap` as separate options? They are exclusive, right?

**Comment by constantinpape** [comment]
>     1. Is this complete?

I think yes.

> 
>     2. Are we happy with it? Now would be a good moment to change something?

From my side it looks mostly good.
I am all in favor in renaming min/maxValue to contrastLimits though.

> 
> 
> I think it is a bit messy, because some of the LayerProperties only apply to the images.json while others only apply to the bookmarks.json. But I think for convenience I may have only one object for this...

Fine with me as long as this works for you.

> 
> Do we need `color` and `colorMap` as separate options? They are exclusive, right?

Yes, they are exclusive. I think we should merge them / just have `color`

**Comment by constantinpape** [comment]
Ok, we just discussed this and agreed on the changes.
I will update the autophagosomes repo later.

**Comment by constantinpape** [comment]
Ok, I have made these changes in the autophagosomes repo.
Note that I have just called it `contrastLimits` now.

**Comment by constantinpape** [comment]
We have implemented all of this now.
Still need to document this properly, see https://github.com/platybrowser/mobie/issues/1.
